[package]
name = "words-are-hard"
version = "0.1.0"
edition = "2021"

[lib]
name = "words-are-hard-"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"

[dependencies]
dialoguer = "0.9"
console = "0.15"
rand = "0.8"