[package]
name = "words-are-imgui"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"

words-are-hard = { path = "../words-are-hard" }
dauga = { path = "../../dauga" }